import type { Metadata } from "next";
import PolicyLayout from "@/components/PolicyLayout";

export const metadata: Metadata = {
  title: "Privacy Policy — DareStake",
  description:
    "What DareStake collects, where it is stored, and who it is shared with.",
};

const CONTACT = "shivansh.goela13@gmail.com";

export default function PrivacyPage() {
  return (
    <PolicyLayout title="Privacy Policy" updated="15 August 2026">
      <p>
        DareStake is a two-person accountability app. You and one partner assign
        each other daily dares; missing a deadline adds a notional fine to a
        shared tally. This page describes exactly what data that requires, where
        it is stored, and who can see it.
      </p>
      <p>
        DareStake is an independent personal project, not a company. There is no
        advertising, no analytics, no tracking pixels, and no third party is ever
        sold or given your data for marketing.
      </p>

      <h2>What we collect</h2>

      <h3>Account information</h3>
      <p>
        When you sign in with Google we receive your <strong>name</strong>,{" "}
        <strong>email address</strong>, <strong>profile photo URL</strong>, and a
        Google account identifier. We use these to identify your account and to
        show your partner who you are. We do not receive or store your Google
        password.
      </p>

      <h3>App data you create</h3>
      <ul>
        <li>
          Dares you assign or are assigned — title, optional description, date,
          deadline, any check-in time, and whether they were completed
        </li>
        <li>
          Your pairing — which account you are paired with, and a pair identifier
        </li>
        <li>
          Streak counts, number of dares completed, and your running fine total
        </li>
        <li>
          Gold Jar entries — the amount and date of each missed dare. This ledger
          is append-only by design: entries cannot be edited or deleted
        </li>
        <li>Emoji reactions and disputes raised on a completed dare</li>
        <li>Whether you have enabled notifications</li>
      </ul>

      <h3>Photo proof (stored in your own Google Drive)</h3>
      <p>
        If you attach a photo as proof of completing a dare, DareStake requests
        the narrow <code>drive.file</code> Google Drive permission and uploads
        the image <strong>to your own Google Drive</strong>. The file is not
        copied to any DareStake server or database — only a reference to it is
        stored so it can be displayed. The <code>drive.file</code> scope only
        grants access to files this app itself creates; it cannot read the rest
        of your Drive. This permission is requested at the moment you first
        attach a photo, not at sign-in.
      </p>

      <h2>What we do not collect</h2>
      <ul>
        <li>
          <strong>No payment information.</strong> Fines in DareStake are a
          shared tally, not a transaction. No card, bank, or UPI details are ever
          requested, and no money moves through the app
        </li>
        <li>No location data</li>
        <li>No contacts, calendar, or device files</li>
        <li>No analytics, advertising, or cross-site tracking</li>
      </ul>

      <h2>Who can see your data</h2>
      <p>
        <strong>Your partner.</strong> This is the point of the app. Once paired,
        your partner can see your dares, whether you completed them, your
        streak, your fine total, and any photo proof you attach. Do not put
        anything in a dare title, description, or photo that you are not
        comfortable sharing with them.
      </p>
      <p>
        <strong>Nobody else.</strong> Access is enforced at the database level:
        every document is scoped to your pair, and requests from outside it are
        rejected by security rules rather than merely hidden in the interface.
      </p>

      <h2>Service providers</h2>
      <p>DareStake runs on third-party infrastructure:</p>
      <ul>
        <li>
          <strong>Google Firebase</strong> (Authentication and Cloud Firestore) —
          stores your account and app data
        </li>
        <li>
          <strong>Google Drive API</strong> — stores photo proof in your own
          Drive, only if you use that feature
        </li>
        <li>
          <strong>Vercel</strong> — hosts the application and processes standard
          web server request logs
        </li>
      </ul>
      <p>
        Each operates under its own privacy policy. Data is held in Google Cloud
        regions selected for the Firebase project.
      </p>

      <h2>Notifications</h2>
      <p>
        Notifications are generated by your own browser through a service worker.
        There is no push server, and notification content is never sent to a
        third party. You can revoke the permission at any time in your browser or
        operating system settings, or turn reminders off in{" "}
        <strong>Profile → Notifications</strong>.
      </p>

      <h2>Retention and deletion</h2>
      <p>
        Data persists while your account exists. Unpairing deactivates the pair
        and clears the link between the two accounts, but retains the dare
        history and the Gold Jar ledger belonging to that pair.
      </p>
      <p>
        There is currently no self-service account deletion. To have your account
        and associated data deleted, email{" "}
        <a href={`mailto:${CONTACT}`}>{CONTACT}</a> from the address you signed
        up with. Photo proof lives in your own Google Drive, so you can delete
        those files yourself at any time.
      </p>

      <h2>Security</h2>
      <p>
        Traffic is served over HTTPS. Authentication is handled by Google, so
        DareStake never sees your password. Database access is restricted by
        pair-scoped security rules. That said, this is a personal project rather
        than an audited commercial service — please treat it accordingly and
        avoid storing anything sensitive in it.
      </p>

      <h2>Children</h2>
      <p>
        DareStake is not intended for children under 13, and we do not knowingly
        collect their data.
      </p>

      <h2>Changes</h2>
      <p>
        If this policy changes materially, the &ldquo;last updated&rdquo; date
        above will change. Continuing to use the app after a change means you
        accept the revised policy.
      </p>

      <h2>Contact</h2>
      <p>
        Questions, or a deletion request:{" "}
        <a href={`mailto:${CONTACT}`}>{CONTACT}</a>
      </p>
    </PolicyLayout>
  );
}
